import { StyleSheet } from 'react-native';
import { colors } from '../../components/ui';
import { sans, sharedStyles } from '../shared/sharedStyles';

const localStyles = StyleSheet.create({
  homeScroll: { paddingBottom: 28 },
  homeHeader: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
  },
  delivery: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  deliveryText: {
    fontFamily: sans,
    color: '#475467',
    fontSize: 13,
    fontWeight: '600',
  },
  deliveryStrong: { color: '#111827', fontWeight: '800' },
  headerIcons: { flexDirection: 'row', gap: 8 },
  referenceSearch: {
    height: 52,
    marginTop: 14,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#F1F3F5',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
  },
  referenceSearchText: {
    fontFamily: sans,
    flex: 1,
    color: '#98A2B3',
    fontSize: 14,
    fontWeight: '600',
  },
  referenceHero: {
    height: 202,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  heroImage: { borderRadius: 20 },
  heroOverlay: { padding: 20, backgroundColor: 'rgba(4, 78, 65, .80)' },
  referenceHeroTitle: {
    fontFamily: sans,
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.6,
  },
  referenceHeroCopy: {
    fontFamily: sans,
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 14,
  },
  referenceSectionLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: 20,
    marginBottom: 20,
  },
  referenceSectionTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  referenceHeading: {
    fontFamily: sans,
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  seeAll: {
    fontFamily: sans,
    color: '#00B879',
    fontSize: 13,
    fontWeight: '800',
  },
  horizontalProducts: { gap: 10, paddingLeft: 16, paddingBottom: 24 },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: 16,
    marginBottom: 25,
  },
  referenceCategory: { width: '25%', alignItems: 'center', gap: 8 },
  referenceCategoryIcon: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#F0FDFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  referenceCategoryText: {
    fontFamily: sans,
    color: '#344054',
    fontSize: 11,
    fontWeight: '700',
  },
  storeScroller: { paddingHorizontal: 16, gap: 15, paddingBottom: 25 },
  officialCard: {
    height: 140,
    width: 128,
    borderWidth: 1,
    borderColor: '#EAECF0',
    borderRadius: 16,
    alignItems: 'center',
    padding: 12,
    gap: 6,
    backgroundColor: '#fff',
  },
  officialIcon: {
    height: 48,
    width: 48,
    borderRadius: 15,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  officialName: {
    fontFamily: sans,
    color: '#111827',
    fontWeight: '800',
    fontSize: 12,
  },
  officialBadge: {
    fontFamily: sans,
    color: '#98A2B3',
    fontWeight: '600',
    fontSize: 11,
  },
  personalizedHeader: {
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  personalizedEyebrow: {
    fontFamily: sans,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '900',
    color: '#0F766E',
    letterSpacing: 1.1,
  },
  personalizedTitle: {
    fontFamily: sans,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    color: '#111827',
    letterSpacing: -0.3,
  },
  recommendGrid: {
    paddingHorizontal: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  recommendCard: { width: '48.4%', marginBottom: 12 },
  recommendImage: { height: 170 },
  trustStrip: {
    marginHorizontal: 16,
    marginTop: 8,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#ECFDF5',
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  trustIcon: {
    width: 31,
    height: 31,
    borderRadius: 16,
    textAlign: 'center',
    lineHeight: 31,
    overflow: 'hidden',
    color: '#fff',
    fontWeight: '900',
    backgroundColor: '#10B981',
  },
  trustTitle: {
    fontFamily: sans,
    color: '#064E3B',
    fontSize: 13,
    fontWeight: '800',
  },
  trustCopy: {
    fontFamily: sans,
    color: '#047857',
    fontSize: 11,
    marginTop: 3,
    lineHeight: 16,
  },
  infoBanner: {
    margin: 16,
    marginTop: 10,
    backgroundColor: '#EFF6FF',
    padding: 16,
    borderRadius: 16,
    gap: 5,
  },
  infoBannerTitle: { color: colors.text, fontWeight: '800' },
  infoBannerText: { color: colors.muted, fontSize: 12, marginBottom: 5 },
  bottomNav: {
    height: 74,
    paddingBottom: 7,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navItem: { alignItems: 'center', minWidth: 55, gap: 2 },
  navLabel: { color: '#94A3B8', fontSize: 10, fontWeight: '600' },
  navActive: { color: colors.primary },
  searchToolbar: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchRoundButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F4F5F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  referenceSearchInput: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#F1F3F5',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchCategoriesContainer: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#EAECF0',
    height: 52,
    flexGrow: 0,
    flexShrink: 0,
  },
  searchCategories: { paddingHorizontal: 16, alignItems: 'center', gap: 2 },
  searchGroupTitle: {
    fontFamily: sans,
    color: '#98A2B3',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
    marginTop: 16,
    marginBottom: 12,
  },
  recentSearches: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 18,
  },
  recentChip: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#EAECF0',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recentText: {
    fontFamily: sans,
    color: '#475467',
    fontWeight: '600',
    fontSize: 13,
  },
  trendingSearches: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  trendingChip: {
    minHeight: 38,
    paddingHorizontal: 14,
    borderRadius: 19,
    backgroundColor: '#E8F8F2',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  trendingText: {
    fontFamily: sans,
    color: '#00B879',
    fontWeight: '700',
    fontSize: 13,
  },
  searchResults: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 104,
    backgroundColor: colors.background,
  },
  resultCount: { color: colors.muted, fontSize: 13, fontWeight: '600', marginBottom: 16 },
  fullCategoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 25,
  },
  fullCategory: {
    backgroundColor: '#fff',
    width: '30.5%',
    minHeight: 108,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    gap: 9,
  },
  fullCategoryIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECFDF5',
  },
  fullCategoryText: {
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '600',
    color: colors.text,
  },
  storeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 13,
    marginVertical: 10,
  },
  storeAvatar: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#047857',
    fontWeight: '800',
    textAlignVertical: 'center',
    textAlign: 'center',
  },
  storeName: { color: colors.text, fontWeight: '800' },
  storeInfo: { color: colors.muted, fontSize: 11, marginTop: 3 },
});

export const styles = { ...sharedStyles, ...localStyles };
