import { StyleSheet } from 'react-native';
import { colors } from '../../components/ui';
import { sans } from './sharedStyles';

export const styles = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  header: {
    height: 61,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
  },
  headerTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  miniProduct: { width: 124 },
  miniImage: { width: 124, height: 113, borderRadius: 14 },
  miniName: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 7,
  },
  miniPrice: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
  },
  referenceProduct: {
    width: 168,
    borderRadius: 14,
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: '#111827',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  referenceProductImage: { width: '100%', height: 150 },
  referenceDiscount: {
    position: 'absolute',
    left: 8,
    top: 8,
    backgroundColor: '#FF3644',
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 10,
  },
  referenceDiscountText: { fontFamily: sans, color: '#fff', fontWeight: '900' },
  referenceHeart: {
    position: 'absolute',
    right: 8,
    top: 8,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  referenceStore: {
    fontFamily: sans,
    marginTop: 10,
    marginHorizontal: 12,
    color: '#667085',
    fontSize: 11,
    fontWeight: '600',
  },
  referenceProductName: {
    fontFamily: sans,
    marginHorizontal: 12,
    marginTop: 4,
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 18,
    minHeight: 36,
  },
  referenceRating: { flexDirection: 'row', marginHorizontal: 12, marginTop: 7 },
  referenceRatingText: {
    fontFamily: sans,
    color: '#667085',
    fontSize: 11,
    marginLeft: 5,
    fontWeight: '700',
  },
  referencePriceLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 12,
    marginTop: 12,
  },
  referencePrice: {
    fontFamily: sans,
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  referenceSold: {
    fontFamily: sans,
    color: '#98A2B3',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'right',
    maxWidth: 60,
  },
  infoRow: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 13,
    alignItems: 'center',
  },
  infoTitle: { color: colors.text, fontWeight: '700', fontSize: 14 },
  infoBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 },
  menuGroup: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 14,
    marginTop: 15,
  },
  menuTitle: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  menu: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 13,
    gap: 12,
  },
  menuLabel: { flex: 1, color: colors.text, fontWeight: '600' },
});
