import { Platform, StyleSheet } from "react-native";
import { colors } from "../../components/ui";

export const sans = Platform.select({
  ios: "System",
  android: "sans-serif",
  web: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
});

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.background },
  page: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: 16, paddingBottom: 28 },
  splash: {
    flex: 1,
    backgroundColor: "#08BFB5",
    alignItems: "center",
    justifyContent: "center",
  },
  splashLogo: {
    width: 128,
    height: 128,
    borderRadius: 38,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.18)",
    marginBottom: 28,
  },
  splashShop: { color: "#fff", fontSize: 58 },
  splashBrand: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 43,
    letterSpacing: -1,
  },
  splashCopy: { color: "#fff", fontWeight: "700", fontSize: 16, marginTop: 7 },
  splashDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 70,
  },
  splashDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "rgba(255,255,255,.55)",
  },
  splashDotActive: {
    width: 33,
    height: 10,
    borderRadius: 6,
    backgroundColor: "rgba(255,255,255,.55)",
  },
  referenceOnboarding: { flex: 1, backgroundColor: "#fff" },
  onboardingGreen: {
    flex: 1,
    minHeight: 430,
    backgroundColor: "#08C7A4",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  bagCircle: {
    width: 125,
    height: 125,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 32,
  },
  bagEmoji: { fontSize: 102 },
  referenceOnboardTitle: {
    fontSize: 31,
    fontWeight: "900",
    color: "#fff",
    textAlign: "center",
    letterSpacing: -0.8,
  },
  referenceOnboardCopy: {
    fontSize: 17,
    lineHeight: 26,
    color: "#fff",
    textAlign: "center",
    marginTop: 23,
    maxWidth: 330,
  },
  onboardingWhite: {
    minHeight: 280,
    padding: 40,
    paddingTop: 50,
    justifyContent: "space-between",
    gap: 27,
  },
  referenceDots: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  referenceDot: {
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: "#E5E7EB",
  },
  referenceDotActive: { width: 34, backgroundColor: colors.primary },
  skipText: {
    textAlign: "center",
    color: "#98A2B3",
    fontWeight: "700",
    fontSize: 16,
  },
  authPage: { flex: 1, backgroundColor: "#fff" },
  referenceAuth: { flexGrow: 1 },
  authHero: {
    minHeight: 340,
    padding: 38,
    paddingTop: 36,
    backgroundColor: "#05AF91",
    justifyContent: "flex-end",
  },
  registerHero: { minHeight: 238, backgroundColor: "#3F61F6" },
  authBack: {
    color: "#fff",
    fontSize: 32,
    position: "absolute",
    top: 34,
    left: 24,
  },
  authStoreIcon: {
    width: 76,
    height: 76,
    borderRadius: 23,
    backgroundColor: "rgba(255,255,255,.18)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 30,
  },
  authStoreGlyph: { color: "#fff", fontSize: 39 },
  authHeroTitle: {
    color: "#fff",
    fontSize: 35,
    fontWeight: "900",
    letterSpacing: -1,
  },
  authHeroCopy: { color: "#fff", fontSize: 19, marginTop: 11, opacity: 0.92 },
  authPanel: { flex: 1, padding: 28, paddingTop: 52, gap: 25 },
  nameRow: { flexDirection: "row", gap: 18 },
  referenceInputWrap: { gap: 11 },
  referenceLabel: {
    color: "#667085",
    fontWeight: "800",
    fontSize: 13,
    letterSpacing: 0.5,
  },
  referenceInput: {
    height: 78,
    borderRadius: 25,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#F1F3F5",
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  referenceInputText: { flex: 1, fontSize: 16, color: "#111827" },
  fieldIcon: { color: "#98A2B3", fontSize: 19 },
  forgot: {
    color: "#00B879",
    fontSize: 15,
    fontWeight: "600",
    textAlign: "right",
    marginTop: -8,
  },
  agreement: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
    marginTop: -4,
  },
  checkbox: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkText: { color: "#fff", fontWeight: "900" },
  agreementText: {
    flex: 1,
    color: "#667085",
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 23,
  },
  agreementLink: { color: "#00B879" },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: -4,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: "#EAECF0" },
  dividerText: { color: "#98A2B3", fontSize: 13 },
  socialRow: { flexDirection: "row", gap: 15, marginTop: -8 },
  socialButton: {
    flex: 1,
    height: 58,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#E4E7EC",
    alignItems: "center",
    justifyContent: "center",
  },
  socialText: { color: "#344054", fontSize: 15, fontWeight: "700" },
  switchAuth: { textAlign: "center", color: "#667085", fontSize: 15 },
  greenLink: { color: "#00B879", fontWeight: "800" },
  back: { color: colors.text, fontSize: 32, lineHeight: 32 },
  homeHeader: {
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
  },
  location: { color: colors.muted, fontSize: 11 },
  locationName: { color: colors.text, fontWeight: "800", marginTop: 2 },
  headerIcons: { flexDirection: "row", gap: 8 },
  searchRow: { flexDirection: "row", gap: 9, marginVertical: 16 },
  hero: {
    minHeight: 166,
    borderRadius: 22,
    padding: 20,
    backgroundColor: "#064E3B",
    overflow: "hidden",
    flexDirection: "row",
    marginBottom: 18,
  },
  heroEyebrow: {
    color: "#6EE7B7",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  heroTitle: {
    color: "#fff",
    fontWeight: "900",
    fontSize: 25,
    lineHeight: 31,
    marginTop: 8,
  },
  heroCta: { color: "#fff", marginTop: 14, fontWeight: "700", fontSize: 12 },
  heroArt: { color: "#A7F3D0", fontSize: 80, transform: [{ rotate: "15deg" }] },
  flash: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 11,
  },
  flashTitle: { color: colors.text, fontSize: 19, fontWeight: "900" },
  flashTimer: { color: "#DC2626", fontSize: 11, marginTop: 2 },
  horizontalProducts: { gap: 10, paddingLeft: 16, paddingBottom: 24 },
  miniProduct: { width: 124 },
  miniImage: { width: 124, height: 113, borderRadius: 14 },
  miniName: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 7,
  },
  miniPrice: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 16,
    marginBottom: 25,
  },
  category: { width: "25%", alignItems: "center", gap: 7, marginBottom: 14 },
  categoryIcon: {
    width: 47,
    height: 47,
    borderRadius: 15,
    backgroundColor: "#ECFDF5",
    alignItems: "center",
    justifyContent: "center",
  },
  categoryText: {
    fontSize: 10,
    color: colors.text,
    textAlign: "center",
    maxWidth: 70,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  infoBanner: {
    margin: 16,
    marginTop: 10,
    backgroundColor: "#EFF6FF",
    padding: 16,
    borderRadius: 16,
    gap: 5,
  },
  infoBannerTitle: { color: colors.text, fontWeight: "800" },
  infoBannerText: { color: colors.muted, fontSize: 12, marginBottom: 5 },
  homeScroll: { paddingBottom: 28 },
  delivery: { flexDirection: "row", alignItems: "center", gap: 8 },
  pin: { color: "#00B879", fontSize: 23 },
  deliveryText: {
    fontFamily: sans,
    color: "#475467",
    fontSize: 15,
    fontWeight: "600",
  },
  deliveryStrong: { color: "#111827", fontWeight: "800" },
  referenceSearch: {
    height: 84,
    marginTop: 17,
    paddingHorizontal: 25,
    marginHorizontal: 16,
    borderRadius: 25,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#F1F3F5",
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
  },
  referenceSearchIcon: { color: "#98A2B3", fontSize: 29 },
  referenceSearchText: {
    fontFamily: sans,
    flex: 1,
    color: "#98A2B3",
    fontSize: 17,
    fontWeight: "600",
  },
  aiChip: {
    width: 45,
    height: 45,
    backgroundColor: "#E8F8F2",
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
  },
  aiText: { fontFamily: sans, color: "#00B879", fontWeight: "800" },
  referenceHero: {
    height: 282,
    marginHorizontal: 16,
    marginTop: 24,
    borderRadius: 31,
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  heroImage: { borderRadius: 31 },
  heroOverlay: { padding: 30, backgroundColor: "rgba(0,132,104,.78)" },
  referenceHeroTitle: {
    fontFamily: sans,
    color: "#fff",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: -0.6,
  },
  referenceHeroCopy: {
    fontFamily: sans,
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginTop: 8,
    marginBottom: 19,
  },
  carouselDots: {
    height: 51,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  carouselActive: {
    height: 9,
    width: 35,
    borderRadius: 6,
    backgroundColor: "#10B981",
  },
  carouselDot: {
    height: 9,
    width: 9,
    borderRadius: 5,
    backgroundColor: "#D0D5DD",
  },
  referenceSectionLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 17,
  },
  referenceSectionTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  flashSymbol: { color: "#FF7A00", fontSize: 31, fontWeight: "900" },
  referenceHeading: {
    fontFamily: sans,
    color: "#111827",
    fontSize: 23,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  timer: {
    paddingHorizontal: 7,
    paddingVertical: 6,
    borderRadius: 5,
    backgroundColor: "#111827",
  },
  seeAll: {
    fontFamily: sans,
    color: "#00B879",
    fontSize: 15,
    fontWeight: "800",
  },
  referenceProduct: {
    width: 255,
    borderRadius: 21,
    backgroundColor: "#fff",
    overflow: "hidden",
    shadowColor: "#111827",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  referenceProductImage: { width: "100%", height: 230 },
  referenceDiscount: {
    position: "absolute",
    left: 14,
    top: 14,
    backgroundColor: "#FF3644",
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 15,
  },
  referenceDiscountText: { fontFamily: sans, color: "#fff", fontWeight: "900" },
  referenceHeart: {
    position: "absolute",
    right: 13,
    top: 13,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  referenceStore: {
    fontFamily: sans,
    marginTop: 17,
    marginHorizontal: 18,
    color: "#667085",
    fontSize: 13,
    fontWeight: "600",
  },
  referenceProductName: {
    fontFamily: sans,
    marginHorizontal: 18,
    marginTop: 4,
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 22,
    minHeight: 44,
  },
  referenceRating: { flexDirection: "row", marginHorizontal: 18, marginTop: 9 },
  referenceRatingText: {
    fontFamily: sans,
    color: "#667085",
    fontSize: 14,
    marginLeft: 7,
    fontWeight: "700",
  },
  referencePriceLine: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    margin: 18,
    marginTop: 17,
  },
  referencePrice: {
    fontFamily: sans,
    color: "#111827",
    fontSize: 21,
    fontWeight: "900",
  },
  referenceSold: {
    fontFamily: sans,
    color: "#98A2B3",
    fontSize: 13,
    fontWeight: "600",
    textAlign: "right",
    maxWidth: 60,
  },
  referenceCategory: { width: "25%", alignItems: "center", gap: 8 },
  referenceCategoryIcon: {
    width: 92,
    height: 92,
    borderRadius: 22,
    backgroundColor: "#F0F4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  referenceCategoryEmoji: { fontSize: 37 },
  referenceCategoryText: {
    fontFamily: sans,
    color: "#344054",
    fontSize: 12,
    fontWeight: "700",
  },
  storeScroller: { paddingHorizontal: 16, gap: 15, paddingBottom: 25 },
  officialCard: {
    height: 167,
    width: 155,
    borderWidth: 1,
    borderColor: "#EAECF0",
    borderRadius: 20,
    alignItems: "center",
    padding: 18,
    gap: 8,
    backgroundColor: "#fff",
  },
  officialIcon: {
    height: 63,
    width: 63,
    borderRadius: 22,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  officialName: {
    fontFamily: sans,
    color: "#111827",
    fontWeight: "800",
    fontSize: 14,
  },
  officialBadge: {
    fontFamily: sans,
    color: "#98A2B3",
    fontWeight: "600",
    fontSize: 13,
  },
  bottomNav: {
    height: 70,
    paddingBottom: 7,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderColor: "#F1F5F9",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  navItem: { alignItems: "center", minWidth: 55, gap: 2 },
  navIcon: { color: "#94A3B8", fontSize: 21 },
  navLabel: { color: "#94A3B8", fontSize: 10, fontWeight: "600" },
  navActive: { color: colors.primary },
  toolbar: {
    padding: 16,
    paddingBottom: 10,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  searchInput: {
    flex: 1,
    height: 45,
    backgroundColor: "#F3F4F6",
    borderRadius: 13,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filter: { fontSize: 22 },
  chips: { padding: 12, paddingTop: 8 },
  resultCount: { color: colors.muted, fontSize: 13, marginBottom: 14 },
  header: {
    height: 61,
    paddingHorizontal: 16,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#F1F5F9",
  },
  headerTitle: { color: colors.text, fontSize: 17, fontWeight: "800" },
  fullCategoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 25,
  },
  fullCategory: {
    backgroundColor: "#fff",
    width: "30.5%",
    minHeight: 108,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    gap: 9,
  },
  fullCategoryIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFDF5",
  },
  fullCategoryText: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: "600",
    color: colors.text,
  },
  detailTop: {
    position: "absolute",
    zIndex: 2,
    left: 16,
    right: 16,
    top: 16,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  floatingBack: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  floatingHeart: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  detailImage: { width: "100%", height: 360, backgroundColor: "#E5E7EB" },
  detailBody: { padding: 16 },
  detailPrice: { color: colors.primary, fontSize: 25, fontWeight: "900" },
  detailName: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 27,
    fontWeight: "800",
    marginTop: 8,
  },
  detailMeta: { flexDirection: "row", marginTop: 8 },
  metaSep: { color: colors.muted, fontSize: 12 },
  detailLine: { height: 1, backgroundColor: colors.line, marginVertical: 18 },
  label: { color: colors.text, fontWeight: "800", marginBottom: 9 },
  variantRow: { flexDirection: "row", marginBottom: 12 },
  infoRow: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  infoIcon: { color: colors.primary, fontSize: 20, width: 23 },
  infoTitle: { color: colors.text, fontWeight: "700", fontSize: 14 },
  infoBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 },
  chevron: { color: "#94A3B8", fontSize: 24 },
  storeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 13,
    marginVertical: 10,
  },
  storeAvatar: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
    color: "#047857",
    fontWeight: "800",
    textAlignVertical: "center",
    textAlign: "center",
  },
  storeName: { color: colors.text, fontWeight: "800" },
  storeInfo: { color: colors.muted, fontSize: 11, marginTop: 3 },
  description: { color: "#4B5563", lineHeight: 21, fontSize: 13 },
  spec: { flexDirection: "row", paddingVertical: 9 },
  specKey: { color: colors.muted, width: "45%" },
  specValue: { color: colors.text, fontWeight: "600" },
  review: { backgroundColor: "#fff", padding: 14, borderRadius: 14, gap: 7 },
  stickyCta: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 83,
    padding: 13,
    backgroundColor: "#fff",
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
    borderTopWidth: 1,
    borderColor: colors.line,
  },
  cartItem: {
    flexDirection: "row",
    gap: 12,
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 16,
    marginBottom: 11,
  },
  cartImage: { height: 82, width: 82, borderRadius: 12 },
  cartName: { color: colors.text, fontWeight: "700", lineHeight: 19 },
  cartFoot: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: "auto",
  },
  checkoutBar: {
    padding: 15,
    backgroundColor: "#fff",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderColor: colors.line,
  },
  total: { fontSize: 18, fontWeight: "900", color: colors.text },
  checkoutCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 15,
    marginBottom: 12,
  },
  addressName: { color: colors.text, fontWeight: "700", marginBottom: 4 },
  summary: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  summaryText: { color: colors.muted, fontSize: 13 },
  summaryBold: { color: colors.text, fontWeight: "900", fontSize: 15 },
  success: {
    flex: 1,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
    gap: 13,
  },
  successIcon: {
    width: 82,
    height: 82,
    borderRadius: 41,
    backgroundColor: "#D1FAE5",
    justifyContent: "center",
    alignItems: "center",
    color: colors.primary,
  },
  successTitle: {
    color: colors.text,
    fontSize: 23,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 8,
  },
  successCopy: {
    color: colors.muted,
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 18,
  },
  profileHero: {
    padding: 18,
    backgroundColor: "#fff",
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: { color: colors.text, fontSize: 17, fontWeight: "900" },
  profileEmail: { color: colors.muted, fontSize: 12, marginTop: 3 },
  menuGroup: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    marginTop: 15,
  },
  menuTitle: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 5,
  },
  menu: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
    gap: 12,
  },
  menuIcon: {
    fontSize: 19,
    color: colors.primary,
    width: 24,
    textAlign: "center",
  },
  notification: {
    marginHorizontal: 16,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    gap: 12,
  },
  notificationIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ECFDF5",
  },
  notificationTitle: { color: colors.text, fontWeight: "800" },
  notificationBody: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  trackingCard: {
    backgroundColor: "#ECFDF5",
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  trackingStatus: {
    color: "#047857",
    fontWeight: "900",
    fontSize: 19,
    marginTop: 6,
  },
  track: {
    flexDirection: "row",
    gap: 13,
    paddingBottom: 25,
    alignItems: "flex-start",
  },
  trackDot: {
    height: 12,
    width: 12,
    borderRadius: 6,
    backgroundColor: "#D1D5DB",
    marginTop: 4,
  },
  trackDotActive: { backgroundColor: colors.primary },
  payment: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  paymentIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#ECFDF5",
    color: "#047857",
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "900",
  },
  storeHero: {
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 22,
    borderRadius: 18,
    gap: 6,
  },
});

