import { StyleSheet } from 'react-native';
import { colors } from '../../components/ui';
import { sharedStyles } from '../shared/sharedStyles';

const localStyles = StyleSheet.create({
  detailTop: {
    position: 'absolute',
    zIndex: 3,
    top: 18,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailTopActions: { flexDirection: 'row', gap: 10 },
  floatingBack: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingAction: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailGallery: { height: 380, backgroundColor: '#F5F5F5' },
  detailImage: { width: '100%', height: '100%', backgroundColor: '#E5E7EB' },
  detailThumbnails: {
    position: 'absolute',
    left: 20,
    bottom: 16,
    flexDirection: 'row',
    gap: 8,
  },
  detailThumbnail: {
    width: 42,
    height: 42,
    borderRadius: 9,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#fff',
  },
  detailThumbnailActive: { borderColor: colors.primary },
  thumbnailImage: { width: '100%', height: '100%' },
  galleryCount: {
    position: 'absolute',
    right: 20,
    bottom: 16,
    backgroundColor: 'rgba(17,24,39,.7)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  galleryCountText: { color: '#fff', fontWeight: '800', fontSize: 12 },
  detailBody: { paddingTop: 24, backgroundColor: '#fff' },
  detailStore: { paddingHorizontal: 20, color: '#667085', fontSize: 13, fontWeight: '700' },
  detailOfficial: { color: colors.primary, fontWeight: '800' },
  detailName: {
    paddingHorizontal: 20,
    color: '#101828',
    fontSize: 21,
    fontWeight: '900',
    marginTop: 7,
  },
  detailPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 12,
    gap: 9,
    flexWrap: 'wrap',
  },
  detailPrice: { color: '#101828', fontSize: 24, fontWeight: '900', flexShrink: 1 },
  detailOldPrice: { color: '#98A2B3', fontSize: 13, textDecorationLine: 'line-through' },
  detailDiscount: { color: '#E11D48', fontSize: 12, fontWeight: '800' },
  detailMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 7,
    marginTop: 10,
  },
  detailRating: { color: '#667085', fontSize: 12, fontWeight: '600' },
  detailSold: { color: '#98A2B3', fontSize: 12, fontWeight: '600' },
  detailSection: { paddingHorizontal: 20, marginTop: 26 },
  variantLabel: { color: '#344054', fontSize: 14, fontWeight: '800' },
  variantValue: { color: '#667085', fontWeight: '500' },
  variantRow: { flexDirection: 'row', gap: 12, marginTop: 12 },
  colorSwatch: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#D0D5DD',
  },
  colorSwatchActive: { borderColor: colors.primary, borderWidth: 4 },
  quantityRow: {
    paddingHorizontal: 20,
    marginTop: 28,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  quantityLabel: { color: '#344054', fontSize: 14, fontWeight: '800' },
  detailQuantityControl: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  detailQuantityButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#F2F4F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailQuantityAdd: { backgroundColor: colors.primary },
  detailQuantityValue: { color: '#344054', fontWeight: '800', minWidth: 15, textAlign: 'center' },
  benefitPanel: { marginHorizontal: 20, marginTop: 32, gap: 14 },
  benefitPrimary: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  benefitTitle: { color: '#1D2939', fontSize: 15, fontWeight: '800' },
  benefitCopy: { color: '#98A2B3', fontSize: 12, fontWeight: '600' },
  benefitSecondary: { flexDirection: 'row', gap: 24, paddingLeft: 2 },
  couponRow: {
    marginHorizontal: 20,
    marginTop: 24,
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#ECFDF5',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  couponText: { flex: 1, color: '#344054', fontSize: 14, fontWeight: '700' },
  couponClaim: { color: colors.primary, fontSize: 14, fontWeight: '800' },
  detailTabs: {
    marginTop: 28,
    borderBottomWidth: 1,
    borderColor: '#EAECF0',
    flexDirection: 'row',
    paddingHorizontal: 20,
  },
  detailTab: { flex: 1, alignItems: 'center', paddingBottom: 12 },
  detailTabText: { color: '#98A2B3', fontSize: 14, fontWeight: '800' },
  detailTabTextActive: { color: colors.primary },
  detailTabIndicator: {
    position: 'absolute',
    bottom: 0,
    width: 45,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  detailDescription: { padding: 20, color: '#4B5563', lineHeight: 21, fontSize: 13 },
  detailSpecs: { padding: 20, gap: 8 },
  detailReview: { margin: 20, backgroundColor: '#F8FAFC', padding: 14, borderRadius: 14, gap: 7 },
  stickyCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 12,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#E5E7EB',
  },
  ctaButton: { flex: 1 },
  cartItem: {
    marginBottom: 12,
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#fff',
    flexDirection: 'row',
    gap: 12,
  },
  cartImage: { height: 82, width: 82, borderRadius: 12 },
  cartName: { color: colors.text, fontWeight: '700', lineHeight: 19 },
  cartFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 9,
  },
  checkoutBar: {
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  total: { fontSize: 18, fontWeight: '900', color: colors.text },
  checkoutCard: { backgroundColor: '#fff', borderRadius: 16, padding: 16, marginBottom: 12 },
  success: {
    flex: 1,
    padding: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  successIcon: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    color: colors.text,
    fontSize: 23,
    fontWeight: '900',
    marginTop: 22,
    textAlign: 'center',
  },
  successCopy: {
    color: colors.muted,
    textAlign: 'center',
    lineHeight: 21,
    marginTop: 9,
    marginBottom: 30,
  },
});

export const styles = { ...sharedStyles, ...localStyles };
