import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  splash: {
    flex: 1,
    backgroundColor: '#0CC7A4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogo: {
    width: 128,
    height: 128,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#061938',
    marginBottom: 28,
    overflow: 'hidden',
  },
  splashLogoImage: { width: '100%', height: '100%' },
  splashBrand: {
    color: '#fff',
    fontWeight: '900',
    fontSize: 43,
    letterSpacing: -1,
  },
  splashCopy: { color: '#fff', fontWeight: '700', fontSize: 16, marginTop: 7 },
  splashDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 70,
  },
  splashDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255,255,255,.55)',
  },
  splashDotActive: {
    width: 33,
    height: 10,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,.55)',
  },
  referenceOnboarding: { flex: 1, backgroundColor: '#fff' },
  onboardingGreen: {
    flex: 1,
    minHeight: 430,
    backgroundColor: '#08C7A4',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  bagCircle: {
    width: 125,
    height: 125,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  referenceOnboardTitle: {
    fontSize: 31,
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: -0.8,
  },
  referenceOnboardCopy: {
    fontSize: 17,
    lineHeight: 26,
    color: '#fff',
    textAlign: 'center',
    marginTop: 23,
    maxWidth: 330,
  },
  onboardingWhite: {
    minHeight: 280,
    padding: 40,
    paddingTop: 50,
    justifyContent: 'space-between',
    gap: 27,
  },
  referenceDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  referenceDot: {
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: '#E5E7EB',
  },
  referenceDotActive: { width: 34, backgroundColor: '#10B981' },
  skipText: {
    textAlign: 'center',
    color: '#98A2B3',
    fontWeight: '700',
    fontSize: 16,
  },
  authPage: { flex: 1, backgroundColor: '#fff' },
  referenceAuth: { flexGrow: 1 },
  loginAuth: { minHeight: '100%' },
  authHero: {
    minHeight: 340,
    padding: 38,
    paddingTop: 36,
    backgroundColor: '#00B894',
    justifyContent: 'flex-end',
  },
  loginAuthHero: { minHeight: 250, height: 250, paddingHorizontal: 28 },
  registerHero: { minHeight: 238, backgroundColor: '#3F61F6' },
  authStoreIcon: {
    width: 76,
    height: 76,
    borderRadius: 23,
    backgroundColor: 'rgba(255,255,255,.18)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  authHeroTitle: {
    color: '#fff',
    fontSize: 35,
    fontWeight: '900',
    letterSpacing: -1,
  },
  loginAuthHeroTitle: { fontSize: 29, letterSpacing: -0.6 },
  authHeroCopy: { color: '#fff', fontSize: 19, marginTop: 11, opacity: 0.92 },
  loginAuthHeroCopy: { fontSize: 16, marginTop: 7 },
  authPanel: { flex: 1, padding: 28, paddingTop: 52, gap: 25 },
  loginAuthPanel: {
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 20,
    gap: 16,
  },
  nameRow: { flexDirection: 'row', gap: 18 },
  referenceInputWrap: { gap: 11 },
  loginInputWrap: { gap: 7 },
  referenceLabel: {
    color: '#667085',
    fontWeight: '800',
    fontSize: 13,
    letterSpacing: 0.5,
  },
  loginInputLabel: { fontSize: 12 },
  referenceInput: {
    height: 78,
    borderRadius: 25,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#F1F3F5',
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loginReferenceInput: { height: 64, borderRadius: 20, paddingHorizontal: 17 },
  referenceInputText: { flex: 1, fontSize: 16, color: '#111827' },
  loginReferenceInputText: { fontSize: 15 },
  forgot: {
    color: '#00B879',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'right',
    marginTop: -8,
  },
  agreement: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'flex-start',
    marginTop: -4,
  },
  checkbox: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#D0D5DD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: { backgroundColor: '#10B981', borderColor: '#10B981' },
  agreementText: {
    flex: 1,
    color: '#667085',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 23,
  },
  agreementLink: { color: '#00B879' },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: -4,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: '#EAECF0' },
  dividerText: { color: '#98A2B3', fontSize: 13 },
  socialRow: { flexDirection: 'row', gap: 15, marginTop: 0 },
  socialButton: {
    flex: 1,
    height: 58,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: '#E4E7EC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  socialText: { color: '#344054', fontSize: 15, fontWeight: '700' },
  switchAuth: { textAlign: 'center', color: '#667085', fontSize: 15 },
  greenLink: { color: '#00B879', fontWeight: '800' },
});
