import { StyleSheet } from 'react-native';
import { colors } from '../../components/ui';
import { sharedStyles } from '../shared/sharedStyles';

const localStyles = StyleSheet.create({
  profileHero: {
    padding: 18,
    backgroundColor: '#fff',
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#D1FAE5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileName: { color: colors.text, fontSize: 17, fontWeight: '900' },
  profileEmail: { color: colors.muted, fontSize: 12, marginTop: 3 },
  notification: {
    marginHorizontal: 16,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    gap: 12,
  },
  notificationIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECFDF5',
  },
  notificationTitle: { color: colors.text, fontWeight: '800' },
  notificationBody: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  trackingCard: {
    backgroundColor: '#ECFDF5',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  trackingStatus: {
    color: '#047857',
    fontWeight: '900',
    fontSize: 19,
    marginTop: 6,
  },
  track: {
    flexDirection: 'row',
    gap: 13,
    paddingBottom: 25,
    alignItems: 'flex-start',
  },
  trackDot: {
    height: 26,
    width: 26,
    borderRadius: 13,
    backgroundColor: '#D1D5DB',
    marginTop: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackDotActive: { backgroundColor: colors.primary },
  payment: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  storeHero: {
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 22,
    borderRadius: 18,
    gap: 6,
  },
  settingsScroll: {
    padding: 16,
    paddingBottom: 40,
    backgroundColor: colors.background,
  },
  settingsGroup: { marginBottom: 24 },
  settingsGroupTitle: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 10,
    marginLeft: 4,
  },
  settingsCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    minHeight: 56,
  },
  settingsIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  settingsRowText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1E293B',
  },
  settingsDivider: { height: 1, backgroundColor: '#F1F5F9' },
});

export const styles = { ...sharedStyles, ...localStyles };
